#!/bin/sh
echo -n "\033[1;31m"
echo "   __ __ __ ______  ____  ____"
echo "  / / ／/ // / __ \/ __ \/ __/"
echo " / / \,/ // / /_/ / /_/ /\ \  "
echo "/_/ \_/\___/_____/\____/___/  "
echo -n "\033[0;39m"

printf "\n"
printf " * GitHub:         https://github.com/Da1sukeKud0\n"
