#!/bin/sh
days=$(expr \( `date -d "20190204" +%s` - `date +%s` \) / 86400)
weeks=$(expr $days / 7)

echo -n "\033[0;31m"
echo -n "We have only "
echo -n "\033[1;31m"
echo -n $days days \($weeks weeks\)
echo -n "\033[0;31m"
echo " to X-Day..."
echo -n "\033[0;39m"
